skip_checks:
  # `PermitAttributes` の警告が出る件の対処。 users_controller#user_params のpassword, password_confirmation で引っかかるが、通常の実装でアリ、Adminメニューであるため問題ないものとする。
  # PermitAttributes は全てスキップされるが、このプロジェクトでは問題ないものと判断する。
  - PermitAttributes


