### Active Storageのファイル保存場所の設定。config/environments/環境名.rb で以下の中から利用するものを選択する。

# 本番環境デプロイの際はconfig/deploy.rbにて「/home/（ユーザー名）/production/shared/storage」にリンクさせる
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
